CREATE TABLE IF NOT EXISTS VerificationCodes (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Email VARCHAR(255) NOT NULL,
    Code VARCHAR(10) NOT NULL,
    ExpiryTime DATETIME NOT NULL,
    IsUsed TINYINT(1) NOT NULL DEFAULT 0
);
